#!/bin/sh

CUR_DIR=`dirname $0`
CUR_DIR=`pwd $CUR_DIR`
cd $CUR_DIR

ORIG_NAME="Twisted-10.2.0"
NAME="python26-twisted"
RELEASE=1
PACKAGER="Nick Bailey - nick@riptano.com"
DOC_FILES="doc/, INSTALL, README, NEWS, LICENSE"
# Specify this because twisted doc files have a python2.2
# reference so we don't want autoreq
REQUIRES="/usr/bin/env, /usr/bin/python2.6"
BUILD_REQUIRES=""

# copy to a directory for building
cp -r $ORIG_NAME $NAME/
#apply any patches
for patch_file in patches/*
do
    patch -p1 -d $NAME < $patch_file
done

# build rpms
cd $NAME
python2.6 setup.py bdist_rpm \
        --python="python2.6" \
        --dist-dir="$CUR_DIR" \
        --release="$RELEASE" \
        --packager="$PACKAGER" \
        --doc-files="$DOC_FILES" \
        --requires="$REQUIRES" \
        --no-autoreq
cd ..

rm -r "$CUR_DIR/$NAME"

